name: "👥 Community Membership Request"
description: Request memeber privileges
labels: ["👥 member"]
title: "team: "

body:
  - type: markdown
    attributes:
      value: |
        Thanks for participating!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
  - type: input
    attributes:
      label: Username
      description: GitHub username for the membership request.
      placeholder: "@username"
    validations:
      required: true
  - type: input
    attributes:
      label: Sponsors
      description: GitHub usernames of sponsors if any.
      placeholder: "@sponsor1, @sponsor2"
    validations:
      required: false
  - type: dropdown
    id: property
    attributes:
      label: Property you'd like to moderate / maintain
      options:
        - General
        - Annex
        - Plugin
        - Package
        - Frontend
        - Social Content
        - Documentation
        - Translations
        - Specific - described below
  - type: textarea
    attributes:
      label: Descripe your role according to the selection above.
      description: Please include your request motivation and role in a community.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional
      description: Optional textarea to provide any additional information.
    validations:
      required: false
  - type: checkboxes
    id: contributing
    attributes:
      label: Contibuting Guide
      description: By submitting this issue, you agree to follow our [Contributing Guide](https://github.com/z-shell/community/blob/main/docs/CONTRIBUTING.md)
      options:
        - label: I aware of project's contributing guide.
          required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/z-shell/community/blob/main/docs/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
