name: "👥 Community Membership Request"
description: Request memeber privileges
labels: ["👥 member"]
title: "team: "

body:
  - type: markdown
    attributes:
      value: |
        Thanks for participating!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
  - type: input
    attributes:
      label: Username
      description: GitHub username for the membership request.
      placeholder: "@username"
    validations:
      required: true
  - type: input
    attributes:
      label: Sponsors
      description: GitHub usernames of sponsors if any.
      placeholder: "@sponsor1, @sponsor2"
    validations:
      required: false
  - type: dropdown
    id: property
    attributes:
      label: "Property you'd like to moderate / maintain / support."
      options:
        - General
        - Annex
        - Plugin
        - Package
        - Frontend
        - Community
        - Documentation
        - Internationalization
        - Other - described below

  - type: textarea
    attributes:
      label: According to the selection above, please descripe your role from your point of view.
      description: >
        "Please try to describe in detail as much as possible, your role in organization, daily routines, what achievent you would set yourself and what steps you would take. Any example is valid"
      required: true

  - type: textarea
    attributes:
      label: Organization support
      description: >
        "Please describe what support you would like from the organization. Anything in relation to above answers is valid."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional
      description: Optional textarea to provide any additional information.
    validations:
      required: false

  - type: checkboxes
    id: contributing
    attributes:
      label: Governance & Steering commitee.
      description: "By submitting this issue, you confirm to agree with [organizational governance and polices for a technical steering committee (TSC)](https://github.com/z-shell/.github/blob/main/governance/README.md)"
      options:
        - label: "I am familiar with and agree with the governance & technical steering committee."
          required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: "By submitting this issue, you agree to follow and will cultivate the [Code of Conduct](https://raw.githubusercontent.com/z-shell/.github/main/governance/organization/CODE-OF-CONDUCT.md)"
      options:
        - label: "I agree to sustain healthy interactions and will follow this project's Code of Conduct."
          required: true
